[build]
  node_version = "22" # Or "20", whichever you prefer. Match your local Node.js version if possible.
  functions = "netlify/functions"
  publish = "."
  base = "/"
[functions]
  directory = "netlify/functions"